// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSStVdEig15jXBYWMNMNX8yCLeVhHNvng',
    appId: '1:591223589431:web:4f8d68bcb52eb343b64db2',
    messagingSenderId: '591223589431',
    projectId: 'sales-bets-79e8a',
    authDomain: 'sales-bets-79e8a.firebaseapp.com',
    storageBucket: 'sales-bets-79e8a.firebasestorage.app',
    measurementId: 'G-QN26HJ4MYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqtWVNuv8fO8khsZfqT6DxyTHGRLtEm0',
    appId: '1:591223589431:android:9d51ca22187676c7b64db2',
    messagingSenderId: '591223589431',
    projectId: 'sales-bets-79e8a',
    storageBucket: 'sales-bets-79e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCqtWVNuv8fO8khsZfqT6DxyTHGRLtEm0', // Same as Android for now
    appId: '1:591223589431:android:9d51ca22187676c7b64db2', // Placeholder - add iOS app to Firebase for real iOS config
    messagingSenderId: '591223589431',
    projectId: 'sales-bets-79e8a',
    storageBucket: 'sales-bets-79e8a.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Add iOS app to Firebase to get this
    iosBundleId: 'com.example.salesBets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCqtWVNuv8fO8khsZfqT6DxyTHGRLtEm0', // Same as Android for now
    appId: '1:591223589431:android:9d51ca22187676c7b64db2', // Placeholder - add macOS app to Firebase for real macOS config
    messagingSenderId: '591223589431',
    projectId: 'sales-bets-79e8a',
    storageBucket: 'sales-bets-79e8a.firebasestorage.app',
    iosClientId: 'YOUR_MACOS_CLIENT_ID', // Add macOS app to Firebase to get this
    iosBundleId: 'com.example.salesBets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSStVdEig15jXBYWMNMNX8yCLeVhHNvng', // Using web config for Windows
    appId: '1:591223589431:web:4f8d68bcb52eb343b64db2', // Using web config for Windows
    messagingSenderId: '591223589431',
    projectId: 'sales-bets-79e8a',
    authDomain: 'sales-bets-79e8a.firebaseapp.com',
    storageBucket: 'sales-bets-79e8a.firebasestorage.app',
    measurementId: 'G-QN26HJ4MYW',
  );
}